barback/urls.py
from django.urls import path
from . import views, static
from .models import Cocktail
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
)

app_name = 'barback'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('cocktail_form/', views.CreateView.as_view(model=Cocktail, success_url=('http://127.0.0.1:8000/barback/')), name='cocktail_form'),
    path('<int:cocktail_id>/save/', views.save, name='save'),
    path('<int:cocktail_id>/delete/', views.delete, name='delete'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='registration/login.html', redirect_field_name=('http://127.0.0.1:8000/barback/')), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('password/', views.change_password, name='change_password'),
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('barback/', include('barback.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

barback/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime
from django.conf import settings
from django.db.models.signals import post_save


class User(AbstractUser):
    pass

class Cocktail(models.Model):
    cocktail_name   = models.CharField(max_length = 50)
    cocktail_image  = models.ImageField(upload_to="cocktail_images/",
                                        blank=True,
                                        null=True)
    pub_date        = models.DateTimeField(auto_now=True)
    cocktail_info   = models.CharField(max_length = 200, blank=True, null=True)
    cocktail_steps  = models.CharField(max_length = 1000, blank=True, null=True)
    virgin          = models.BooleanField(null=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE,
                                              blank=True,
                                              null=True)

    cocktail_type_choices = (
        ('WHISKEY', 'Whiskey'),
        ('VODKA', 'Vodka'),
        ('TEQUILA', 'Tequila'),
        ('GIN', 'Gin'),
        ('VIRGIN', 'Virgin'),
    )
    cocktail_type = models.CharField(max_length = 10, choices = cocktail_type_choices)

    def __str__(self):
        return self.cocktail_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=2) <= self.pub_date <= now

    def get_absolute_url(self):
        return reverse("barback:detail", kwargs={"id": self.id})

    @classmethod
    def manhattan(cls):
        manhattan = cls.objects.create(cocktail_name  = "manhattan",
                                       cocktail_info  = "a classic drink",
                                       cocktail_steps = "shake it in a shaker",
                                       cocktail_type  = "Whiskey",
                                       virgin         =  False,)
        return manhattan

    @classmethod
    def martini(cls):
        martini = cls.objects.create(cocktail_name  = "martini",
                                       cocktail_info  = "youve seen bond",
                                       cocktail_steps = "shaken, not stirred",
                                       cocktail_type  = "Vodka",
                                       virgin         =  False,)
        return martini

    @classmethod
    def get_by_type(cls, type):
        cocktails = cls.objects.filter(cocktail_type = type)
        return cocktails

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = User.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

barback/forms.py
from django import forms
from .models import Cocktail, User
from django.db import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CocktailForm(forms.ModelForm):

    class Meta:
        model = Cocktail
        fields = [
            "cocktail_name",
            "cocktail_image",
            "cocktail_type",
            "cocktail_info",
            "cocktail_steps",
            "virgin",
            "user",
        ]

    def save(self, commit=True):
        cocktail                = super(CocktailForm, self).save(commit=False)
        cocktail.cocktail_name  = self.cleaned_data['cocktail_name']
        cocktail.cocktail_info  = self.cleaned_data['cocktail_info']
        cocktail.cocktail_steps = self.cleaned_data['cocktail_steps']

        if commit:
            cocktail.save()

        return cocktail

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def save(self, commit=True):
        user            = super(UserForm, self).save(commit=False)
        user.username   = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name  = self.cleaned_data['last_name']
        user.email      = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'password',
        ]

barback/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic, View
from django.utils import timezone
from .models import Cocktail, User
from django.db import models
from django.contrib import messages
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.template import loader
from django.urls import reverse
import datetime
from .forms import (
    CocktailForm,
    UserForm,
    EditProfileForm,
)
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm
)
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    update_session_auth_hash
)
from django.contrib.auth.models import User

class IndexView(generic.ListView):
    template_name = 'barback/index.html'
    context_object_name = 'latest_cocktails'

    def get_queryset(self):
        return Cocktail.objects.order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Cocktail
    template_name = 'barback/detail.html'

    def get_queryset(self):
        return Cocktail.objects.filter(pub_date__lte=timezone.now())

class CreateView(generic.edit.CreateView):
    model = Cocktail
    fields = ['cocktail_name',
              'cocktail_type',
              'cocktail_image',
              'cocktail_info',
              'cocktail_steps',
              'virgin',
              ]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AboutView(generic.TemplateView):
    template_name = "barback/about.html"

class ProfileView(generic.ListView):
    template_name = 'barback/profile.html'
    context_object_name = 'user_cocktails'

    def get_queryset(self):
        return Cocktail.objects.filter(user=self.request.user).order_by('-pub_date')

class RegisterView(generic.edit.CreateView):
    template_name = 'registration/registration_form.html'
    form_class    = UserForm

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = "Username is already taken"
    return JsonResponse(data)

def save(request, cocktail_id):
    form = CocktailForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse('barback:detail', args=(cocktail.id,)))

def delete(request, cocktail_id):
    model = get_object_or_404(Cocktail, pk=cocktail_id)
    model.delete()
    return HttpResponseRedirect(reverse('barback:index'))

def logout_view(request):
    logout(request)
    return redirect('barback:index')

def edit_profile(request):
    template_name = 'barback/edit_profile.html'
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('barback:profile')
    else:
        form = EditProfileForm(instance=request.user)
        return render(request, template_name, {'form': form})

def change_password(request):
    template_name = 'barback/password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('barback:profile')
        else:
            return redirect('barback:password')
    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, template_name, {'form': form})

barback/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-danger">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barback:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barback:index' %}">Cocktails</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="{% url 'barback:index' %}">Barback</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'barback:profile' %}">{{ request.user.username }}</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barback:logout' %}">Sign Out</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barback:register' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'barback:login' %}">Sign In</a>
                </li>
              {% endif %}
            </ul>
        </div>
    </nav>
    <link rel="stylesheet" href="{% static 'barback/css/style.css' %}">
    {%block body%}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'barback/javascript/filter-search.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>