barback/urls.py
from django.urls import path
from . import views, static
from .models import Cocktail
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
)

app_name = 'barback'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('cocktail_form/', views.CreateView.as_view(model=Cocktail, success_url=('http://127.0.0.1:8000/barback/')), name='cocktail_form'),
    path('<int:cocktail_id>/save/', views.save, name='save'),
    path('<int:cocktail_id>/delete/', views.delete, name='delete'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='registration/login.html', redirect_field_name=('http://127.0.0.1:8000/barback/')), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('password/', views.change_password, name='change_password'),
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('barback/', include('barback.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

barback/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import datetime
from django.conf import settings
from django.db.models.signals import post_save


class User(AbstractUser):
    pass

class Cocktail(models.Model):
    cocktail_name   = models.CharField(max_length = 50)
    cocktail_image  = models.ImageField(upload_to="cocktail_images/",
                                        blank=True,
                                        null=True)
    pub_date        = models.DateTimeField(auto_now=True)
    cocktail_info   = models.CharField(max_length = 200, blank=True, null=True)
    cocktail_steps  = models.CharField(max_length = 1000, blank=True, null=True)
    virgin          = models.BooleanField(null=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE,
                                              blank=True,
                                              null=True)

    cocktail_type_choices = (
        ('WHISKEY', 'Whiskey'),
        ('VODKA', 'Vodka'),
        ('TEQUILA', 'Tequila'),
        ('GIN', 'Gin'),
        ('VIRGIN', 'Virgin'),
    )
    cocktail_type = models.CharField(max_length = 10, choices = cocktail_type_choices)

    def __str__(self):
        return self.cocktail_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=2) <= self.pub_date <= now

    def get_absolute_url(self):
        return reverse("barback:detail", kwargs={"id": self.id})

    @classmethod
    def manhattan(cls):
        manhattan = cls.objects.create(cocktail_name  = "manhattan",
                                       cocktail_info  = "a classic drink",
                                       cocktail_steps = "shake it in a shaker",
                                       cocktail_type  = "Whiskey",
                                       virgin         =  False,)
        return manhattan

    @classmethod
    def martini(cls):
        martini = cls.objects.create(cocktail_name  = "martini",
                                       cocktail_info  = "youve seen bond",
                                       cocktail_steps = "shaken, not stirred",
                                       cocktail_type  = "Vodka",
                                       virgin         =  False,)
        return martini

    @classmethod
    def get_by_type(cls, type):
        cocktails = cls.objects.filter(cocktail_type = type)
        return cocktails

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = User.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

barback/forms.py
from django import forms
from .models import Cocktail, User
from django.db import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CocktailForm(forms.ModelForm):

    class Meta:
        model = Cocktail
        fields = [
            "cocktail_name",
            "cocktail_image",
            "cocktail_type",
            "cocktail_info",
            "cocktail_steps",
            "virgin",
            "user",
        ]

    def save(self, commit=True):
        cocktail                = super(CocktailForm, self).save(commit=False)
        cocktail.cocktail_name  = self.cleaned_data['cocktail_name']
        cocktail.cocktail_info  = self.cleaned_data['cocktail_info']
        cocktail.cocktail_steps = self.cleaned_data['cocktail_steps']

        if commit:
            cocktail.save()

        return cocktail

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def save(self, commit=True):
        user            = super(UserForm, self).save(commit=False)
        user.username   = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name  = self.cleaned_data['last_name']
        user.email      = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'password',
        ]

barback/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic, View
from django.utils import timezone
from .models import Cocktail, User
from django.db import models
from django.contrib import messages
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.template import loader
from django.urls import reverse
import datetime
from .forms import (
    CocktailForm,
    UserForm,
    EditProfileForm,
)
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm
)
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    update_session_auth_hash
)
from django.contrib.auth.models import User

class IndexView(generic.ListView):
    template_name = 'barback/index.html'
    context_object_name = 'latest_cocktails'

    def get_queryset(self):
        return Cocktail.objects.order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Cocktail
    template_name = 'barback/detail.html'

    def get_queryset(self):
        return Cocktail.objects.filter(pub_date__lte=timezone.now())

class CreateView(generic.edit.CreateView):
    model = Cocktail
    fields = ['cocktail_name',
              'cocktail_type',
              'cocktail_image',
              'cocktail_info',
              'cocktail_steps',
              'virgin',
              ]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AboutView(generic.TemplateView):
    template_name = "barback/about.html"

class ProfileView(generic.ListView):
    template_name = 'barback/profile.html'
    context_object_name = 'user_cocktails'

    def get_queryset(self):
        return Cocktail.objects.filter(user=self.request.user).order_by('-pub_date')

class RegisterView(generic.edit.CreateView):
    template_name = 'registration/registration_form.html'
    form_class    = UserForm

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = "Username is already taken"
    return JsonResponse(data)

def save(request, cocktail_id):
    form = CocktailForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse('barback:detail', args=(cocktail.id,)))

def delete(request, cocktail_id):
    model = get_object_or_404(Cocktail, pk=cocktail_id)
    model.delete()
    return HttpResponseRedirect(reverse('barback:index'))

def logout_view(request):
    logout(request)
    return redirect('barback:index')

def edit_profile(request):
    template_name = 'barback/edit_profile.html'
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('barback:profile')
    else:
        form = EditProfileForm(instance=request.user)
        return render(request, template_name, {'form': form})

def change_password(request):
    template_name = 'barback/password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('barback:profile')
        else:
            return redirect('barback:password')
    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, template_name, {'form': form})

barback/templates/barback/about.html
{% extends 'base.html' %}
<head>
  {% block head %}
  <title>About</title>
  {% endblock %}
</head>
<body>
  {% block body %}
  {% load static %}
    <div class="container">
      <h1>About Barback</h1>

      <p>information about barback</p>
    </div>
  {% endblock %}
</body>

barback/templates/barback/cocktail_form.html
{% extends 'base.html' %}
<!-- <head>
  {{ form.media }}
</head> -->
{% block body %}
<h2>Create your cocktail</h2>
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}
{% block javascript %}

{% endblock %}

barback/templates/barback/delete.html
<h3>Delete Cocktail?</h3>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Yes">
</form>

barback/templates/barback/detail.html
{% extends 'base.html' %}
<head>
  {% block head %}
  <title>{{ cocktail.cocktail_name }}</title>
  {% endblock %}
</head>

{% block body %}
{% load static %}
<div class="container">
  <link rel="stylesheet" type="text/css" href="{% static 'barback/style.css' %}">
  <img src="{{ cocktail.cocktail_image.url }}" alt="img" width="240">
  <h1>{{ cocktail.cocktail_name }}</h1>
  <p>{{ cocktail.pub_date }}</p>
  <p>{{ cocktail.user.username }}</p>

  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <h3>{{ cocktail.cocktail_type }}</h3>
  <h2>how to create</h2>
  <p>{{ cocktail.cocktail_steps }}</p>
  {% if cocktail.user == request.user %}
    <a href="{% url 'barback:delete' cocktail.id  %}">delete</a>
  {% endif %}
</div>

{% endblock %}

barback/templates/barback/edit_profile.html
{% extends 'base.html' %}

{% block head %}
  <title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <body>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save Changes</button>
    </form>
  </body>
</div>
{% endblock %}

barback/templates/barback/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  {% block head %}
  <title>Barback</title>
  {% endblock %}
</head>
<body>
  {% block body %}
  <div class="container">
    <h1 class="display-2">Cocktails</h1>
    <div id="search">
      <input type="text" placeholder=" search cocktail" id="filter-search">
    </div>
    <a href="{% url 'barback:cocktail_form' %}">Create a cocktail</a>
  </div>
  <div class="container">
    <ul class="nav nav-tabs">
      <li class='nav-item'>
        <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all"
           role="tab" aria-controls="all" aria-selected="true">
          All Cocktails
        </a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
        {% if latest_cocktails %}
        {% for cocktail in latest_cocktails %}
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 recipe" id="{{ cocktail.cocktail_name }}">
          <a href="{% url 'barback:detail' cocktail.id %}">
            <div class="card">
              <img src="{{ cocktail.cocktail_image.url }}" class="card-img-top"
              height="185" width="278">
              <div class="card-body">
                <a href="{% url 'barback:detail' cocktail.id %}">
                  <h5 class="card-title text-center">{{ cocktail.cocktail_name }}</h5>
                </a>
                <p class="card-text text-center">{{ cocktail.cocktail_info }}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
        {% else %}
          <p>No cocktails!</p>
        {% endif %}
      </div>
    </div>
  </div>
  {% endblock %}

  {% block javascript %}
  {% endblock %}
</body>
</html>

barback/templates/barback/password.html
{% extends 'base.html' %}

{% block head %}
  <title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <body>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save Password</button>
    </form>
  </body>
</div>
{% endblock %}

barback/templates/barback/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  <body>
    <p>{{user}}</p>
    <p>{{user.first_name}}</p>
    <p>{{user.last_name}}</p>
    <p>{{user.email}}</p>
    <a href="{% url 'barback:edit_profile' %}">edit</a>
    <ul class="nav nav-tabs">
      <li class='nav-item'>
        <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all"
           role="tab" aria-controls="all" aria-selected="true">
           All Cocktails
        </a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
        {% if user_cocktails %}
          {% for cocktail in user_cocktails %}
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 recipe" id="{{ cocktail.cocktail_name }}">
              <div class="card">
                <img src="{{ cocktail.cocktail_image.url }}" class="card-img-top"
                     height="185" width="278">
                <div class="card-body">
                  <a href="{% url 'barback:detail' cocktail.id %}">
                    <h5 class="card-title text-center">{{ cocktail.cocktail_name }}</h5>
                  </a>
                  <p class="card-text text-center">{{ cocktail.cocktail_info }}</p>
                </div>
              </div>
            </div>
         {% endfor %}
        {% else %}
          <p>You have not created any Cocktails</p>
        {% endif %}
      </div>
    <div class="tab-content" id="myTabContent">
  </body>
</div>
{% endblock %}